inferno-framework/inferno-framework.github.io

- README.md
- index.html
Adds redirect to `/inferno-core` and updates README.
No testing possible.  I confirmed that this will not interfere with the existing /inferno-core content, and should just make it so that https://inferno-framework.github.io no longer is a 404.
> Update README and add redirect.

- docs/deployment/database.md
- docs/deployment/index.md
Requirements met for fulfilling ticket [FI-2091](https://oncprojectracking.healthit.gov/support/browse/FI-2091) for this repo.
Let me know if we need to change [database.md#L28](https://github.com/inferno-framework/inferno-framework.github.io/blob/36ef74824d15563e37d94f68da60ca2558f95659/docs/deployment/database.md?plain=1#L28) and similar lines to docker compose -- Since the docker-compose is now a built in under docker compose, I'm not sure it makes sense to say that we are using docker-compose here, but wasn't fully sure.
> FI-2091 Replaced docker-compose with docker compose

- docs/concepts.md
- docs/deployment/host.md
- docs/deployment/index.md
- docs/index.md
- index_new.html
Addressed most of the typo and grammar points from the FI-2033 Documentation Review feedback page.
The only thing I did not know how to fix was the string that appears in the browser tab.  If you go to https://inferno-framework.github.io/index_new.html and look at the tab, it is just "Inferno Framework - " instead of something like "Inferno Framework - Home".  
None
> FI-2033 Minor typo and grammar fixes

- docs/deployment/database.md
Copy over a note about DB replication which I guess I didn't realize was on the wrong docs site.
See the bottom of `database.md`  from before it was just deleted: https://github.com/inferno-framework/inferno-core/pull/486/files#diff-be33c680b614ca4ad400108673f732a4d4dab24b6e796c7045a8546354c7d958
> Copy postgres replication note from old docs site

- docs/getting-started/inferno-cli.md
Fix a minor typo in the documentation for Inferno Command Line Interface
Should say "Interface" instead of "Interface"
> Fix typo in command line docs

- docs/writing-tests/making-requests.md
Synchronizes [available fhir methods in the documentation site](http://localhost:4000/docs/writing-tests/making-requests.html#fhir-requests) with the [library documentation](https://inferno-framework.github.io/inferno-core/docs/Inferno/DSL/FHIRClient.html).  Caught by Pavel on [Zulip](https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Question.20regarding.20Web.20UI.20for.20multiple.20test.20kits/near/440370998).
I built and served locally and this is what it looks like now:
> Update available fhir methods in documentation.

- docs/getting-started/inferno-cli.md
This is dependent on inferno-framework/inferno-core#502 getting merged and in being in the next Inferno core release. **Do not merge this until that PR is merged.**
Once we support `bundle exec inferno start` it should no longer be noted as an exemption to the `bundle exec` rule, but I kept it as a warning in case people are using older versions of Inferno. Please advise if there's a better way to handle this.
> Update Inferno CLI docs for bundle exec inferno start

- docs/getting-started/index.md
Just clarifying the link to the tutorial on creating test kits to not imply it is a tutorial on using the existing US Core test kit.
Also trying out a quick workflow where we just edit changes to the doc site from GitHub.
> Improve language in link to test kit authoring tutorial

- assets/common.css
Icon is shown when hovering over h2-h5 header elements in docs, but was positioned such that user couldn't mouse over and copy the link. This fixes that behavior.
It also keeps the link positioned next to the header when resizing the window. If the windows shrinks < 881px, then the icon is moved to the right side of the header element, since there is no longer enough margin on the left to show the icon.
View documentation pages, and hover over header elements (h2-h5 only) 
Red URL icon should appear next to the header. Move the mouse over the icon and verify you can copy the URL for that fragment.
Resize the window < 880px and > 880px and note the behavior of the icon. Verify it is accessible by mouse in both cases (you can hover on the icon and copy the url)
> Adjust anchor link icons so user can copy url

- docs/getting-started/index.md
- docs/getting-started/inferno-cli.md
Added docs for the `inferno new` command to /docs/getting-started and /docs/getting-started/inferno-cli
Now Getting Started mentions using `inferno new` to create Test Kit template as option to cloning. 
Inferno CLI page lists inferno new in the command table and includes paragraphs describing the feature.
Verify links to the Inferno CLI page on the Getting Started page are correct. 
Verify inferno new is in CLI command table
Verify description of using inferno new is correct on CLI page.
> Add documentation of the inferno new command

- community/resources.md
- docs/getting-started/index.md
Inferno Test Kit authoring Tutorial has moved from inferno-training to inferno-framework project.
Update links in getting started and community resources pages.
Verify links now point to GitHub.com/inferno-framework/tutorial-test-kit/wiki
> FI-3368 Update links to test kit tutorial

- docs/advanced-test-features/configuration-checks.md
- docs/advanced-test-features/custom-banner.md
- docs/advanced-test-features/index.md
- docs/advanced-test-features/input-presets.md
- docs/advanced-test-features/scratch.md
- docs/advanced-test-features/serving-http-requests.md
- docs/advanced-test-features/test-configuration.md
- docs/advanced-test-features/waiting-for-requests.md
- docs/concepts.md
- docs/deployment/index.md
- docs/getting-started-users.md
- docs/index.md
- docs/writing-tests/properties.md
Some documentation edits from the minor_updates branch were left unmerged. This PR brings forward the documentation updates which are still relevant. https://github.com/inferno-framework/inferno-framework.github.io/pull/37 can be closed after this is merged.
Review language updates on Documentation Introduction and Key Concepts pages.
Advanced Features has brought forward Input Presets to be the first topic.
Getting Started no longer refers to the deprecated FHIR Validator wrapper.
Deploying to shared hosts points to HL7 Wrapper repository.
> FI-3277 Bring forward updates from minor_updates branch

- docs/advanced-test-features/using-test-kits-in-ci-cd.md
- docs/ci-cd-usage.md
- docs/getting-started/inferno-cli.md
- docs/writing-tests/properties.md
Documentation for `inferno execute`, `short id`, and running test kits in CI/CD. A news update will be a separate PR.
Please review
> FI-3442 execute cli docs

- docs/distributing-tests.md
Update the distributing tests section of the docs to reflect recent changes in core. This should only be merged after merging inferno-framework/inferno-core#578, releasing the next inferno core version, and releasing a new inferno template.
1. checkout this branch
2. `bundle exec jekyll serve`
3. go to <http://127.0.0.1:4000/docs/distributing-tests.html>
> update distributing tests docs

- docs/getting-started/index.md
- docs/getting-started/inferno-cli.md
- Replace `inferno start --watch` with `bundle exec inferno start --watch` in getting started.
- Update Inferno-CLI docs to be explicit about bundle exec
Please review the diff and this screenshot of the table:
> Fix bundle exec start

- docs/writing-tests/index.md
Add instructions on importing existing Test Kits to the Writing Tests documentation.
Review /docs/writing-tests for instructions on adding external Test Kits to your Test Kit
> FI-2612 Add instructions on importing Test Kits

- docs/getting-started/inferno-cli.md
- docs/writing-tests/fhir-validation.md
Added documentation on using the evaluator CLI to the "Inferno CLI" documentation page. Also added examples to run the evaluator as a sub section.
This isn't necessarily the long term home for this documentation since use of the Evaluator may not be in the context of "Creating Test Kits", but we can put it there for now.
> FI-4030, 4031: Add documentation for the evaluator CLI

- docs/advanced-test-features/waiting-for-requests.md
`bundle exec jekyll s` then navigate to `http://localhost:4000/docs/advanced-test-features/waiting-for-requests.html#advanced-incoming-request-handling` to view the documentation.
> FI-4241: Add documentation for suite endpoints

- Gemfile.lock
- docs/writing-tests/test-inputs-outputs.md
This PR updates the Inputs and Outputs documentation to include missing input properties:
* `hidden`
* Also adds a section on input merging behavior (probably should in AuthInfo doc ticket?).
run `bundle exec jekyll serve ` and go to `http://localhost:4000/docs/writing-tests/test-inputs-outputs.html`
> FI-4232: Document Missing Input Properties

- Gemfile.lock
- docs/getting-started/inferno-cli.md
This PR updates the CLI documentation to add missing implemented commands and options, including:
* Coverage of `evaluate`, `suite describe`, `input_template`, and `lock_short_ids` commands
* Additional evaluator CLI options: `--data-path`, `--output`, `--config`
run `bundle exec jekyll serve` and go to `http://localhost:4000/docs/getting-started/inferno-cli.html` to inspect the changes.
> FI-4229: Update CLI Commands Documentation

- docs/advanced-test-features/test-configuration.md
- docs/writing-tests/properties.md
This PR adds documentation for manipulating runnable children (`remove`, `replace`,` reorder`), as well as Suite link helpers (`add_link`, `source_code_url`,` ig_url`, `download_url`, `report_issue_url`).
> FI-4233: Runnable Child Manipulation and Suite Link Helpers  Documentation
